### ISSUE TITLE
NoSuchMethodError from JsonRelay

### ISSUE THREAD

**Issue by strong-code** [hammerlab/spark-json-relay#10]
Hi there - I'm running json-relay/slim/spree stack against a spark 2.0 cluster in standalone mode. I'm executing scripts through jupyterhub notebooks (pyspark-shell process) and have been receiving this error causing all scripts to crash.

In the pyspark submit args, i'm following the example here with:

```
--packages org.hammerlab:spark-json-relay:2.0.1
--conf spark.extraListeners=org.apache.spark.JsonRelay
```

I am able to create the sparkContext but it will crash as soon as I create and perform an action on a dataframe (in this instance, running a SQLQuery):

```
spark = SparkSession\
    .builder\
    .appName("test01")\
    .getOrCreate()

a = SQLQuery(spark, 'schema', 'user', SQL_BASIC_INFO)
df_users = a.fetch_sql()
df_users.persist()
```

Stack trace below

```
16/09/30 22:19:10 ERROR util.Utils: uncaught error in thread SparkListenerBus, stopping SparkContext
java.lang.NoSuchMethodError: org.apache.spark.scheduler.SparkListenerExecutorMetricsUpdate.taskMetrics()Lscala/collection/Seq;
    at org.apache.spark.JsonRelay.onEvent(JsonRelay.scala:51)
    at org.apache.spark.SparkFirehoseListener.onExecutorMetricsUpdate(SparkFirehoseListener.java:103)
    at org.apache.spark.scheduler.SparkListenerBus$class.doPostEvent(SparkListenerBus.scala:59)
    at org.apache.spark.scheduler.LiveListenerBus.doPostEvent(LiveListenerBus.scala:35)
    at org.apache.spark.scheduler.LiveListenerBus.doPostEvent(LiveListenerBus.scala:35)
    at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:63)
    at org.apache.spark.scheduler.LiveListenerBus.postToAll(LiveListenerBus.scala:35)
    at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(LiveListenerBus.scala:81)
    at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:66)
    at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:66)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
    at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(LiveListenerBus.scala:65)
    at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1229)
    at org.apache.spark.scheduler.LiveListenerBus$$anon$1.run(LiveListenerBus.scala:64)
```

Hopefully someone can provide some insight into why this is crashing the sparkcontext. I would love to get this stack up and running in a stable way.

**Comment by sadikovi** [comment]
I think Spree officially supports <= Spark 1.5, it works on 1.6, since API has not changed for listeners and all. The problem with 2.0 is that API is changed slightly. 

Here is `taskMetrics` in 1.6 https://github.com/apache/spark/blob/branch-1.6/core/src/main/scala/org/apache/spark/scheduler/SparkListener.scala#L112

Became `accumUpdates` in current master (and 2.0): https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/scheduler/SparkListener.scala#L119

Therefore fails with no such method error. I think we should add full support for Spark 2.0. But for now you can patch code manually, just update couple of files:

``` diff
diff --git a/build.sbt b/build.sbt
index 8335770..6f87049 100644
--- a/build.sbt
+++ b/build.sbt
@@ -10,4 +10,4 @@ libraryDependencies += json4s

 spName := "hammerlab/spark-json-relay"

-sparkVersion := "1.5.0"
+sparkVersion := "2.0.0"
diff --git a/src/main/scala/org/apache/spark/JsonRelay.scala b/src/main/scala/org/apache/spark/JsonRelay.scala
index eccd029..e9aec94 100644
--- a/src/main/scala/org/apache/spark/JsonRelay.scala
+++ b/src/main/scala/org/apache/spark/JsonRelay.scala
@@ -9,7 +9,7 @@ import org.json4s.jackson.JsonMethods._
 import org.json4s.JsonDSL._
 import org.apache.spark.scheduler.{SparkListenerExecutorMetricsUpdate, SparkListenerEvent}
 import org.apache.spark.util.{Utils, JsonProtocol}
-import org.json4s.JsonAST.{JObject, JNothing, JValue}
+import org.json4s.JsonAST.{JArray, JObject, JNothing, JValue}

 class JsonRelay(conf: SparkConf) extends SparkFirehoseListener {

@@ -48,15 +48,15 @@ class JsonRelay(conf: SparkConf) extends SparkFirehoseListener {
       // spark-core:1.5.0, which seems worse than just duplicating the code
       // path here.
       case e: SparkListenerExecutorMetricsUpdate =>
-        if (e.taskMetrics.nonEmpty)
+        if (e.accumUpdates.nonEmpty)
           ("Event" -> Utils.getFormattedClassName(e)) ~
             ("Executor ID" -> e.execId) ~
-            ("Metrics Updated" -> e.taskMetrics.map {
-              case (taskId, stageId, attemptId, metrics) =>
+            ("Metrics Updated" -> e.accumUpdates.map {
+              case (taskId, stageId, attemptId, updates) =>
                 ("Task ID" -> taskId) ~
                   ("Stage ID" -> stageId) ~
                   ("Stage Attempt ID" -> attemptId) ~
-                  ("Task Metrics" -> JsonProtocol.taskMetricsToJson(metrics))
+                  ("Task Metrics" -> JArray(updates.map(JsonProtocol.accumulableInfoToJson).toList))
             })
         else
           JNothing

```

I have not tested this on Spark 2.0, so it would be good to know if these changes worked:)

**Comment by strong-code** [comment]
Thanks @sadikovi 

I'll fork & patch and report back with results later this week. Appreciate the help!

**Comment by sadikovi** [comment]
No worries.

Sorry to say that:) but it might require a little bit more changes, since `accumulableInfoToJson` gives you different information compare to `taskMetricsToJson`. That patch will make it compiled, but you might get wrong metrics or none in Spark UI. 

Plus, it is worth checking that other JSON objects are the same compare to Spark 1.5/6. I am happy to help with this port to Spark 2.0.

Thanks for experimenting with this, we should definitely fix it and add support for Spark 2.0.

**Comment by sadikovi** [comment]
@strong-code any news on Spark 2.0 integration?

**Comment by strong-code** [comment]
Unfortunately I have not had a lot of time to work on this, and I'm not too familiar with Scala either. I may have to defer to someone else with more scala+spark knowledge than me.

**Comment by sadikovi** [comment]
All good, no worries:) I am not sure what the plan around update is either.
