### ISSUE TITLE
jackson-annotations.jar not found in spark 1.5.2

### ISSUE THREAD

**Issue by jinxuan** [hammerlab/spark-json-relay#7]
I'm trying to install spree and got stucked when trying to load jsonRelay package.

Here is the command I used.

```
jinxuans-mbp:spark-1.5.2-bin-hadoop2.6 jinxuanwu$ ./bin/spark-shell  --packages org.hammerlab:spark-json-relay:2.0.1 --conf spark.extraListeners=org.apache.spark.JsonRelay
```

And I got the following error, 

```
Ivy Default Cache set to: /Users/jinxuanwu/.ivy2/cache
The jars for the packages stored in: /Users/jinxuanwu/.ivy2/jars
:: loading settings :: url = jar:file:/Users/jinxuanwu/spark-1.5.2-bin-hadoop2.6/lib/spark-assembly-1.5.2-hadoop2.6.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
org.hammerlab#spark-json-relay added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
    confs: [default]
    found org.hammerlab#spark-json-relay;2.0.1 in central
    found org.json4s#json4s-jackson_2.10;3.2.10 in list
    found org.json4s#json4s-core_2.10;3.2.10 in list
    found org.json4s#json4s-ast_2.10;3.2.10 in list
    found com.thoughtworks.paranamer#paranamer;2.6 in list
    found com.fasterxml.jackson.core#jackson-databind;2.3.1 in local-m2-cache
    found com.fasterxml.jackson.core#jackson-annotations;2.3.0 in local-m2-cache
    found com.fasterxml.jackson.core#jackson-core;2.3.1 in local-m2-cache
    found org.scala-lang#scalap;2.10.4 in central
    found org.scala-lang#scala-compiler;2.10.4 in list
    found org.scala-lang#scala-reflect;2.10.4 in list
downloading https://repo1.maven.org/maven2/org/hammerlab/spark-json-relay/2.0.1/spark-json-relay-2.0.1.jar ...
    [SUCCESSFUL ] org.hammerlab#spark-json-relay;2.0.1!spark-json-relay.jar (116ms)
:: resolution report :: resolve 2187ms :: artifacts dl 128ms
    :: modules in use:
    com.fasterxml.jackson.core#jackson-annotations;2.3.0 from local-m2-cache in [default]
    com.fasterxml.jackson.core#jackson-core;2.3.1 from local-m2-cache in [default]
    com.fasterxml.jackson.core#jackson-databind;2.3.1 from local-m2-cache in [default]
    com.thoughtworks.paranamer#paranamer;2.6 from list in [default]
    org.hammerlab#spark-json-relay;2.0.1 from central in [default]
    org.json4s#json4s-ast_2.10;3.2.10 from list in [default]
    org.json4s#json4s-core_2.10;3.2.10 from list in [default]
    org.json4s#json4s-jackson_2.10;3.2.10 from list in [default]
    org.scala-lang#scala-compiler;2.10.4 from list in [default]
    org.scala-lang#scala-reflect;2.10.4 from list in [default]
    org.scala-lang#scalap;2.10.4 from central in [default]
    :: evicted modules:
    org.scala-lang#scalap;2.10.0 by [org.scala-lang#scalap;2.10.4] in [default]
    ---------------------------------------------------------------------
    |                  |            modules            ||   artifacts   |
    |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
    ---------------------------------------------------------------------
    |      default     |   12  |   1   |   1   |   1   ||   11  |   1   |
    ---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
        [NOT FOUND  ] com.fasterxml.jackson.core#jackson-annotations;2.3.0!jackson-annotations.jar(bundle) (1ms)

    ==== local-m2-cache: tried

      file:/Users/jinxuanwu/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.3.0/jackson-annotations-2.3.0.jar

        ::::::::::::::::::::::::::::::::::::::::::::::

        ::              FAILED DOWNLOADS            ::

        :: ^ see resolution messages for details  ^ ::

        ::::::::::::::::::::::::::::::::::::::::::::::

        :: com.fasterxml.jackson.core#jackson-annotations;2.3.0!jackson-annotations.jar(bundle)

        ::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
    unknown resolver null


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [download failed: com.fasterxml.jackson.core#jackson-annotations;2.3.0!jackson-annotations.jar(bundle)]
    at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1011)
    at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:286)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:153)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

Could you please help me with this?

**Comment by sadikovi** [comment]
Is it still relevant? I was able to download it without any problems.
